/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shaoqiu_luajava_LuaState */

#ifndef _Included_com_shaoqiu_luajava_LuaState
#define _Included_com_shaoqiu_luajava_LuaState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shaoqiu_luajava_LuaState
 * Method:    _luaL_newstate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_shaoqiu_luajava_LuaState__1luaL_1newstate
  (JNIEnv *, jobject);

/*
 * Class:     com_shaoqiu_luajava_LuaState
 * Method:    _luaL_openlibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_shaoqiu_luajava_LuaState__1luaL_1openlibs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_shaoqiu_luajava_LuaState
 * Method:    _luaL_dofile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_shaoqiu_luajava_LuaState__1luaL_1dofile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_shaoqiu_luajava_LuaState
 * Method:    _get_global_integer
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_shaoqiu_luajava_LuaState__1get_1global_1integer
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_shaoqiu_luajava_LuaState
 * Method:    _get_global_string
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shaoqiu_luajava_LuaState__1get_1global_1string
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
